# Autogenerated by devscripts/update-version.py

__version__ = '2024.03.15.205633'

RELEASE_GIT_HEAD = 'eb76328c631cd20e414eb1a935e341871ec91ccb'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'coletdjnz/yt-dlp-dev'

ORIGIN = 'coletdjnz/yt-dlp-dev'

_pkg_version = '2024.03.15.205633'
